name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_flask:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install Flask

    - name: Run Flask app
      run: |
        source venv/bin/activate
        export FLASK_RUN_PORT=5001
        export FLASK_APP=app.py
        flask run & 
        APP_PID=$!
        echo "Flask app started with PID $APP_PID"

    - name: Monitor Flask app
      run: |
        while pgrep flask > /dev/null; do
          sleep 5
        done
        echo "Flask app has stopped"
