name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_flask:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install Flask

    - name: Run Flask app
      run: |
        source venv/bin/activate
        export FLASK_APP=app.py
        flask run & 
        APP_PID=$!
        echo "Flask app started with PID $APP_PID"

    - name: Wait for user input
      run: |
        read -p "Press any key to stop the Flask app..."
        kill $APP_PID
